openapi: 3.1.1
info:
  title: Beckn Contract Schema
  description: Schema definition for Contract in the Beckn Protocol v2.1
  version: 2.1.0
  contact:
    name: Beckn Labs
    url: https://beckn.io
  license:
    name: CC-BY-NC-SA 4.0 International
    url: https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en
components:
  schemas:
    BecknLdContext:
      description: This is a reserved JSON-LD property containing a URL to the reference vocabulary where this schema has been defined. If missing, this field defaults to `https://schema.beckn.io/#`. It allows applications to fetch the mapping between the simple JSON keys of this class and absolute Beckn IRIs (Internationalized Resource Identifiers), allowing conversion of standard Beckn JSON payload into linked data. It provides semantic context, allowing machines to understand, expand, and interpret the values in the Beckn vocabulary. These Beckn IRIs are often further mapped to globally used, referencing vocabularies like schema.org. If this value is equal to https://schema.beckn.io/#, then the mapping can be found at `https://schema.beckn.io/context.jsonld`. Furthermore, the ontology of the Beckn schema, can be found at `https://schema.beckn.io/vocab.jsonld`. However, the same cannot be said for other vocabularies like schema.org.
      type: string
      format: uri
      default: https://schema.beckn.io/

    BecknLdType:
      description: This is a string that contains a Beckn IRI on the vocabulary defined in the @context. This type enforces @type to be an IRI-like string that MUST start with "beckn:" and MUST contain exactly one colon. (i.e., "beckn:<Word2>"). Word2 is restricted to URL-safe-ish identifier characters (alphanum, "_", "-", ".", "~").
      type: string
      pattern: '^beckn:[A-Za-z0-9._~-]+$'
      default: beckn:Contract


    Contract:
      description: This is a JSON-LD compliant, linked-data schema that specifies a generic multi-party, digitally signed Contract between a set of participants. based on the vocabulary defined in the @context. By default, it is the most generic form of contract i.e beckn:Contract. However, based on the mapping being used in @context, it could take values like retail:Order, mobility:Reservation, healthcare:Appointment, and so on, which will be defined as sub-classes of beckn:Contract. 
      type: object
      properties:
        '@context':
          $ref: 'https://schema.beckn.io/BecknLdContext/ref'
        '@type':
          $ref: 'https://schema.beckn.io/BecknLdType/ref'
        id:
          description: A UUID string generated at the BPP endpoint at any stage before the confirmation of the order i.e before `/on_confirm` callback. This value is intended typically for indexing or filtering. This value may or may not be the same as `id` which is intended purely for machine-readability. While the chances of a UUID collision are rare, it is recommended to use a combination of `bppId` (i.e, its FQDN), `providerId` and `id`` to allow for global uniqueness. 
          type: string
          format: uuid
        displayId:
          description: A human-readable / Agent-readable identifier of the contract intended for display or printing. This value may or may be different from `id` which is intended purely for machine-readability. Typically, this value is generated after the confirmation of the order at the BPP's end. Furthermore, this value can be generated either by the BPP application or by any downstream provider application that has integrated with the BPP. In any case, the BPP must ensure that this value is unique within the domain boundary of the BPP. 
          type: string
        items:
          description: The items of value i.e resources, specified in this contract. Depending upon the context, these resources could be a combination physical objects, virtual objects, services, time slots, distance travelled, alloted space, and many more. 
          type: array
          items:
            $ref: 'https://schema.beckn.io/Resource/ref'
          minItems: 1
        status:
          description: The current state of the contract. Depending on the context, it could be just a code or a detailed description of state. 
          oneOf:
            - type: string
              description: A single code describing the status of the contract. What this string can hold, can be found by navigating the context.jsonld of the closest parent object. 
            - type: object
              properties:
                '@context':
                  $ref: 'https://schema.beckn.io/BecknLdContext/ref'
                '@type':
                  $ref: 'https://schema.beckn.io/BecknLdType/ref'
                contractValue:
                  description: An object that captures the total value of the contract. In its simplest sense, it can contain a breakup of the items in the order, along with any discounts, fulfillment charges, and any other additional charges relevant to that context. 
                  type: object
        participants:
          type: array
          items:
            $ref: '#/components/schemas/Participant'
        terms:
          type: array
          items:
            $ref: '#/components/schemas/Policy'
        fulfillments:
          description: Describes the acts performed by each participant to fulfill the contract
          type: array
          items:
            allOf:
            - $ref: '#/components/schemas/Fulfillment'
      required:
      - '@type'
      - participants
      - contractItems
      additionalProperties: false
